services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: distribusense
      POSTGRES_USER: distribusense
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    environment:
      PYTHONPATH: /app
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  streamlit:
    build: .
    command: streamlit run app/dashboard/streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    env_file: .env
    environment:
      PYTHONPATH: /app
    ports:
      - "8502:8501"
    depends_on:
      - api

volumes:
  postgres_data: